version: "2"
services:
  web:
    build: .
    command: bash -c "npm install -no-bin-links && nodemon --debug=5858"
    depends_on:
      - "redis"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "5858:5858"
  redis:
    image: redis
    entrypoint: redis-server --appendonly yes
    volumes: 
      - ./data:/data 
    expose:
      - "6379"