version: "2"
services:
  web:
    image: sztwiorok/wybory
    depends_on:
      - "redis"
    ports:
      - "80:8000"
  redis:
    image: redis
    entrypoint: redis-server --appendonly yes
    volumes: 
      - ./data:/data 
    expose:
      - "6379"